=== dthiers/webs4/Week 2/Practicum/starwars.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="starWarsEntity">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="species" type="xs:string"/>
      <xs:element name="language" type="xs:string"/>
      <xs:element name="home" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="wookieType">
    <xs:complexContent>
      <!-- hier overerven -->
      <xs:extension base="starWarsEntity">
        <xs:sequence>
          <!-- hier nieuwe shit toevoegen aan nieuwe complexType -->
          <xs:element name="battleCry" type="xs:string"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>


  <xs:element name="gallery"/>

</xs:schema>

=== dthiers/webs4/Week 2/Practicum/gallery.xml
<?xml version="1.0" encoding="UTF-8"?>
<gallery xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="starwars.xsd">

  <character xsi:type="starWarsEntity">
    <name>Test</name>
    <species>Test</species>
    <language>Test</language>
    <home>Test</home>
  </character>

  <character xsi:type="wookieType">
    <name>Test1</name>
    <species>Test1</species>
    <language>Test1</language>
    <home>Test1</home>
    <battleCry>Test1</battleCry>
  </character>
</gallery>
